### ISSUE TITLE
When I try to instantiate the ParallelCrawlerEngine, I get "Your current AbotX license does not include Auto Tuning."

### ISSUE THREAD

**Issue by sjdirect** [sjdirect/abotx#9]
User reported...

-------------------------------User Reported------------------------------

When I try to instantiate the ParallelCrawlerEngine, I get the below exception.  However, I checked the value of AutoTuning.IsEnabled, and it's set to false.  So is AutoThrottling.IsEnabled.

The version of AbotX installed is:  1.2.28, installed via NuGet.  This also occurred with the previous version, which I believe was 1.1.x

Also, beginning with version 1.2.28, I now get a warning about my call of the ParallelCrawlerEngine's constructor being obsolete.  Here is my current constructor call:

var crawlEngine = new ParallelCrawlerEngine(cx, abotFactory, null, siteToCrawlProvider);

Intellisense says that I should be using a constructor that refers to a 'ParallelImplementationOverride' - what's that about?

-------------------------------Stack Trace------------------------------

System.UnauthorizedAccessException was unhandled by user code
  HResult=-2147024891
  Message=Your current AbotX license does not include Auto Tuning. Please change AutoTuning.IsEnabled to false or upgrade your license.
  Source=AbotX
  StackTrace:
       at AbotX.Core.HostStressAnalyzerCpu.CheckLicense()
       at AbotX.Core.HostStressAnalyzerCpu..ctor(CrawlConfigurationX config, ICpuSampler cpuSampler)
       at AbotX.Parallel.ParallelImplementationOverride..ctor(CrawlConfigurationX config, ParallelImplementationContainer impls)
       at AbotX.Parallel.ParallelCrawlerEngine..ctor(CrawlConfigurationX config, IWebCrawlerFactory webCrawlerFactory, IRateLimiter rateLimiter, ISiteToCrawlProvider siteToCrawlProvider)
       at lsSiteCrawler.Crawler.MultipleSitesCrawler.Crawl(Boolean bLoadCSS) in C:\Users\rjones\Documents\Visual Studio 2015\Projects\lsSiteCrawler\src\lsSiteCrawler\Crawler\SiteCrawler.cs:line 797
       at lsSiteCrawler.Controllers.HarvestedLinksController.Post() in C:\Users\rjones\Documents\Visual Studio 2015\Projects\lsSiteCrawler\src\lsSiteCrawler\Controllers\HarvestedLinksController.cs:line 218
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException:

**Comment by sjdirect** [comment]
Nuget v1.2.33 should solve this issue. Waiting for verification.

**Comment by sjdirect** [comment]
Turns out the error was still happening after the 1.2.33. Tracked it back to config Section handler problem when certain config values were missing. Nuget v1.2.42 should fix this now. Will verify with user.
